#!/usr/bin/env bash
# A Bash script that prints "To infinity and beyond" indefinitely and reacts to SIGTERM

term_handler() {
    echo "I am invincible!!!"
}

# Trap SIGTERM signal and call term_handler
trap 'term_handler' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
