#!/usr/bin/env bash
# This script displays a message indefinitely and resists SIGTERM signals
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
#!/usr/bin/env bash
# This script sends a SIGTERM signal to the 7-highlander process
pkill -f 7-highlander